		if self.toolButton_38.text() != "請指定選股條件":
			if self.toolButton_38.text() in ['(日)K線','(週)K線','(月)K線']:
				if str(sql_table_name[input_name.index(self.toolButton_38.text())]) == 'DayStockInformation':
					total_output.append(['T8',str(sql_table_name[input_name.index(self.toolButton_10.text())]),str(sql_field_name[input_name.index(self.toolButton_38.text())]),str(sql_field_name[input_name.index(self.toolButton_10.text())]),str(sql_table_name[input_name.index(self.toolButton_38.text())]),'Y8',filter8.IsPreviousDay(),filter8.IsLastDay(), ''])
				elif str(sql_table_name[input_name.index(self.toolButton_38.text())]) == 'WeekStockInformation':
					total_output.append(['T8',str(sql_table_name[input_name.index(self.toolButton_10.text())]),str(sql_field_name[input_name.index(self.toolButton_38.text())]),str(sql_field_name[input_name.index(self.toolButton_10.text())]),str(sql_table_name[input_name.index(self.toolButton_38.text())]),'Y8',filter8.IsPreviousWeek(),filter8.IsLastWeek(), ''])
				elif str(sql_table_name[input_name.index(self.toolButton_38.text())]) == 'MonthStockInformation':
					total_output.append(['T8',str(sql_table_name[input_name.index(self.toolButton_10.text())]),str(sql_field_name[input_name.index(self.toolButton_38.text())]),str(sql_field_name[input_name.index(self.toolButton_10.text())]),str(sql_table_name[input_name.index(self.toolButton_38.text())]),'Y8',filter8.IsPreviousMonth(),filter8.IsLastMonth(), ''])
			elif self.toolButton_38.text() in ['(日)RSI(6)/RSI(9)','(週)RSI(6)/RSI(9)','(月)RSI(6)/RSI(9)']:
				if str(sql_table_name[input_name.index(self.toolButton_38.text())]) == 'DayStockInformation':
					total_output.append(['T8',str(sql_table_name[input_name.index(self.toolButton_10.text())]).split('|')[0],str(sql_field_name[input_name.index(self.toolButton_38.text())]).split('|')[0],str(sql_field_name[input_name.index(self.toolButton_38.text())]).split('|')[1],str(sql_table_name[input_name.index(self.toolButton_38.text())]),'Y8',filter8.IsPreviousDay(),filter8.IsLastDay(),tuple(str(sql_field_name[input_name.index(self.toolButton_10.text())]).split('|')), ''])
				elif str(sql_table_name[input_name.index(self.toolButton_38.text())]) == 'WeekStockInformation':
					total_output.append(['T8',str(sql_table_name[input_name.index(self.toolButton_10.text())]).split('|')[0],str(sql_field_name[input_name.index(self.toolButton_38.text())]).split('|')[0],str(sql_field_name[input_name.index(self.toolButton_38.text())]).split('|')[1],str(sql_table_name[input_name.index(self.toolButton_38.text())]),'Y8',filter8.IsPreviousWeek(),filter8.IsLastWeek(),tuple(str(sql_field_name[input_name.index(self.toolButton_10.text())]).split('|')), ''])
				elif str(sql_table_name[input_name.index(self.toolButton_38.text())]) == 'MonthStockInformation':
	 				total_output.append(['T8',str(sql_table_name[input_name.index(self.toolButton_10.text())]).split('|')[0],str(sql_field_name[input_name.index(self.toolButton_38.text())]).split('|')[0],str(sql_field_name[input_name.index(self.toolButton_38.text())]).split('|')[1],str(sql_table_name[input_name.index(self.toolButton_38.text())]),'Y8',filter8.IsPreviousMonth(),filter8.IsLastMonth(),tuple(str(sql_field_name[input_name.index(self.toolButton_10.text())]).split('|')), ''])
			elif self.toolButton_38.text() in ['(日)K(9)/D(9)','(週)K(9)/D(9)','(月)K(9)/D(9)']:
				if str(sql_table_name[input_name.index(self.toolButton_38.text())]) == 'DayStockInformation':
					total_output.append(['T8',str(sql_table_name[input_name.index(self.toolButton_10.text())]).split('|')[1],str(sql_field_name[input_name.index(self.toolButton_38.text())]).split('|')[0],str(sql_field_name[input_name.index(self.toolButton_38.text())]).split('|')[1],str(sql_table_name[input_name.index(self.toolButton_38.text())]),'Y8',filter8.IsPreviousDay(),filter8.IsLastDay(),tuple(str(sql_field_name[input_name.index(self.toolButton_10.text())]).split('|')), ''])
				elif str(sql_table_name[input_name.index(self.toolButton_38.text())]) == 'WeekStockInformation':
					total_output.append(['T8',str(sql_table_name[input_name.index(self.toolButton_10.text())]).split('|')[1],str(sql_field_name[input_name.index(self.toolButton_38.text())]).split('|')[0],str(sql_field_name[input_name.index(self.toolButton_38.text())]).split('|')[1],str(sql_table_name[input_name.index(self.toolButton_38.text())]),'Y8',filter8.IsPreviousWeek(),filter8.IsLastWeek(),tuple(str(sql_field_name[input_name.index(self.toolButton_10.text())]).split('|')), ''])
				elif str(sql_table_name[input_name.index(self.toolButton_38.text())]) == 'MonthStockInformation':
	 				total_output.append(['T8',str(sql_table_name[input_name.index(self.toolButton_10.text())]).split('|')[1],str(sql_field_name[input_name.index(self.toolButton_38.text())]).split('|')[0],str(sql_field_name[input_name.index(self.toolButton_38.text())]).split('|')[1],str(sql_table_name[input_name.index(self.toolButton_38.text())]),'Y8',filter8.IsPreviousMonth(),filter8.IsLastMonth(),tuple(str(sql_field_name[input_name.index(self.toolButton_10.text())]).split('|')), ''])
			elif self.toolButton_38.text() in ['(日)MACD/DIF','(週)MACD/DIF','(月)MACD/DIF']:
				if str(sql_table_name[input_name.index(self.toolButton_38.text())]) == 'DayStockInformation':
					total_output.append(['T8',str(sql_table_name[input_name.index(self.toolButton_38.text())]),str(sql_field_name[input_name.index(self.toolButton_38.text())]).split('|')[0],str(sql_field_name[input_name.index(self.toolButton_38.text())]).split('|')[1],'',(sql_table_name[input_name.index(self.toolButton_10.text())],sql_field_name[input_name.index(self.toolButton_10.text())]), filter8.IsLastDay()])
				elif str(sql_table_name[input_name.index(self.toolButton_38.text())]) == 'WeekStockInformation':
					total_output.append(['T8',str(sql_table_name[input_name.index(self.toolButton_38.text())]),str(sql_field_name[input_name.index(self.toolButton_38.text())]).split('|')[0],str(sql_field_name[input_name.index(self.toolButton_38.text())]).split('|')[1],'',(sql_table_name[input_name.index(self.toolButton_10.text())],sql_field_name[input_name.index(self.toolButton_10.text())]), filter8.IsLastWeek()])
				elif str(sql_table_name[input_name.index(self.toolButton_38.text())]) == 'MonthStockInformation':
	 				total_output.append(['T8',str(sql_table_name[input_name.index(self.toolButton_38.text())]),str(sql_field_name[input_name.index(self.toolButton_38.text())]).split('|')[0],str(sql_field_name[input_name.index(self.toolButton_38.text())]).split('|')[1],'',(sql_table_name[input_name.index(self.toolButton_10.text())],sql_field_name[input_name.index(self.toolButton_10.text())]), filter8.IsLastMonth()])
			else:
				if str(sql_table_name[input_name.index(self.toolButton_38.text())]) == 'DayStockInformation':
					total_output.append(['T8',str(sql_table_name[input_name.index(self.toolButton_38.text())]),str(sql_field_name[input_name.index(self.toolButton_38.text())]),'NOT',(sql_table_name[input_name.index(self.toolButton_10.text())],sql_field_name[input_name.index(self.toolButton_10.text())]), filter8.IsLastDay()])
				elif str(sql_table_name[input_name.index(self.toolButton_38.text())]) == 'WeekStockInformation':
					total_output.append(['T8',str(sql_table_name[input_name.index(self.toolButton_38.text())]),str(sql_field_name[input_name.index(self.toolButton_38.text())]),'NOT',(sql_table_name[input_name.index(self.toolButton_10.text())],sql_field_name[input_name.index(self.toolButton_10.text())]), filter8.IsLastWeek()])
				elif str(sql_table_name[input_name.index(self.toolButton_38.text())]) == 'MonthStockInformation':
	 				total_output.append(['T8',str(sql_table_name[input_name.index(self.toolButton_38.text())]),str(sql_field_name[input_name.index(self.toolButton_38.text())]),'NOT',(sql_table_name[input_name.index(self.toolButton_10.text())],sql_field_name[input_name.index(self.toolButton_10.text())]), filter8.IsLastMonth()])