        self.label_51.setText("月K")
        self.comboBox_13.setItemText(0, ">")
        self.comboBox_13.setItemText(1, ">=")
        self.comboBox_13.setItemText(2, "<")
        self.comboBox_13.setItemText(3, "<=")
        self.comboBox_13.setItemText(4, "<>")
        self.comboBox_13.setItemText(5, "=")
        self.lineEdit_6.setText("0")
        self.label_35.setText(" 連續")
        self.comboBox_15.setItemText(0, "1")
        self.comboBox_15.setItemText(1, "2")
        self.comboBox_15.setItemText(2, "3")
        self.comboBox_15.setItemText(3, "4")
        self.comboBox_15.setItemText(4, "5")
        self.comboBox_15.setItemText(5, "6")
        self.comboBox_15.setItemText(6, "7")
        self.comboBox_15.setItemText(7, "8")
        self.comboBox_15.setItemText(8, "9")
        self.comboBox_15.setItemText(9, "10")
        self.label_36.setText("月")
        self.label_53.setText("日KD")
        self.comboBox_16.setItemText(0, "黃金交叉")
        self.comboBox_16.setItemText(1, "低於20黃金交叉")
        self.comboBox_16.setItemText(2, "20~50黃金交叉")
        self.comboBox_16.setItemText(3, "50~80黃金交叉")
        self.comboBox_16.setItemText(4, "高於80黃金交叉")
        self.comboBox_16.setItemText(5, "死亡交叉")
        self.comboBox_16.setItemText(6, "低於20死亡交叉")
        self.comboBox_16.setItemText(7, "20~50死亡交叉")
        self.comboBox_16.setItemText(8, "50~80死亡交叉")
        self.comboBox_16.setItemText(9, "高於80死亡交叉")
        self.label_55.setText("週KD")
        self.comboBox_140.setItemText(0, "黃金交叉")
        self.comboBox_140.setItemText(1, "低於20黃金交叉")
        self.comboBox_140.setItemText(2, "20~50黃金交叉")
        self.comboBox_140.setItemText(3, "50~80黃金交叉")
        self.comboBox_140.setItemText(4, "高於80黃金交叉")
        self.comboBox_140.setItemText(5, "死亡交叉")
        self.comboBox_140.setItemText(6, "低於20死亡交叉")
        self.comboBox_140.setItemText(7, "20~50死亡交叉")
        self.comboBox_140.setItemText(8, "50~80死亡交叉")
        self.comboBox_140.setItemText(9, "高於80死亡交叉")
        self.label_57.setText("月KD")
        self.comboBox_154.setItemText(0, "黃金交叉")
        self.comboBox_154.setItemText(1, "低於20黃金交叉")
        self.comboBox_154.setItemText(2, "20~50黃金交叉")
        self.comboBox_154.setItemText(3, "50~80黃金交叉")
        self.comboBox_154.setItemText(4, "高於80黃金交叉")
        self.comboBox_154.setItemText(5, "死亡交叉")
        self.comboBox_154.setItemText(6, "低於20死亡交叉")
        self.comboBox_154.setItemText(7, "20~50死亡交叉")
        self.comboBox_154.setItemText(8, "50~80死亡交叉")
        self.comboBox_154.setItemText(9, "高於80死亡交叉")
        self.label_59.setText("日D")
        self.comboBox_17.setItemText(0, ">")
        self.comboBox_17.setItemText(1, ">=")
        self.comboBox_17.setItemText(2, "<")
        self.comboBox_17.setItemText(3, "<=")
        self.comboBox_17.setItemText(4, "<>")
        self.comboBox_17.setItemText(5, "=")
        self.lineEdit_40.setText("0")
        self.label_216.setText(" 連續")
        self.comboBox_139.setItemText(0, "1")
        self.comboBox_139.setItemText(1, "2")
        self.comboBox_139.setItemText(2, "3")
        self.comboBox_139.setItemText(3, "4")
        self.comboBox_139.setItemText(4, "5")
        self.comboBox_139.setItemText(5, "6")
        self.comboBox_139.setItemText(6, "7")
        self.comboBox_139.setItemText(7, "8")
        self.comboBox_139.setItemText(8, "9")
        self.comboBox_139.setItemText(9, "10")
        self.label_218.setText("天")
        self.label_62.setText("週D")
        self.comboBox_18.setItemText(0, ">")
        self.comboBox_18.setItemText(1, ">=")
        self.comboBox_18.setItemText(2, "<")
        self.comboBox_18.setItemText(3, "<=")
        self.comboBox_18.setItemText(4, "<>")
        self.comboBox_18.setItemText(5, "=")
        self.lineEdit_39.setText("0")
        self.label_215.setText(" 連續")
        self.comboBox_21.setItemText(0, "1")
        self.comboBox_21.setItemText(1, "2")
        self.comboBox_21.setItemText(2, "3")
        self.comboBox_21.setItemText(3, "4")
        self.comboBox_21.setItemText(4, "5")
        self.comboBox_21.setItemText(5, "6")
        self.comboBox_21.setItemText(6, "7")
        self.comboBox_21.setItemText(7, "8")
        self.comboBox_21.setItemText(8, "9")
        self.comboBox_21.setItemText(9, "10")
        self.label_217.setText("週")
        self.label_65.setText("月D")
        self.comboBox_19.setItemText(0, ">")
        self.comboBox_19.setItemText(1, ">=")
        self.comboBox_19.setItemText(2, "<")
        self.comboBox_19.setItemText(3, "<=")
        self.comboBox_19.setItemText(4, "<>")
        self.comboBox_19.setItemText(5, "=")
        self.lineEdit_38.setText("0")
        self.label_214.setText(" 連續")
        self.comboBox_20.setItemText(0, "1")
        self.comboBox_20.setItemText(1, "2")
        self.comboBox_20.setItemText(2, "3")
        self.comboBox_20.setItemText(3, "4")
        self.comboBox_20.setItemText(4, "5")
        self.comboBox_20.setItemText(5, "6")
        self.comboBox_20.setItemText(6, "7")
        self.comboBox_20.setItemText(7, "8")
        self.comboBox_20.setItemText(8, "9")
        self.comboBox_20.setItemText(9, "10")
        self.label_219.setText("月")
        self.label_160.setText("日MACD 落點")
        self.label_56.setText("：DIF、MACD")
        self.comboBox_34.setItemText(0, "大於")
        self.comboBox_34.setItemText(1, "小於")
        self.label_48.setText("0")
        self.label_164.setText("月MACD 落點")
        self.label_66.setText("：DIF、MACD")
        self.comboBox_39.setItemText(0, "大於")
        self.comboBox_39.setItemText(1, "小於")
        self.label_52.setText("0")
        self.label_162.setText("週MACD 落點")
        self.label_58.setText("：DIF、MACD")
        self.comboBox_37.setItemText(0, "大於")
        self.comboBox_37.setItemText(1, "小於")
        self.label_50.setText("0")
        self.label_191.setText("日MACD,日DIF")
        self.comboBox_45.setItemText(0, "黃金交叉")
        self.comboBox_45.setItemText(1, "死亡交叉")
        self.label_207.setText("週MACD,週DIF")
        self.comboBox_44.setItemText(0, "黃金交叉")
        self.comboBox_44.setItemText(1, "死亡交叉")
        self.label_185.setText("月MACD,月DIF")
        self.comboBox_38.setItemText(0, "黃金交叉")
        self.comboBox_38.setItemText(1, "死亡交叉")
        self.label_68.setText("日MACD")
        self.comboBox_22.setItemText(0, ">")
        self.comboBox_22.setItemText(1, ">=")
        self.comboBox_22.setItemText(2, "<")
        self.comboBox_22.setItemText(3, "<=")
        self.comboBox_22.setItemText(4, "<>")
        self.comboBox_22.setItemText(5, "=")
        self.lineEdit.setText("0")
        self.label_6.setText(" 連續")
        self.comboBox_23.setItemText(0, "1")
        self.comboBox_23.setItemText(1, "2")
        self.comboBox_23.setItemText(2, "3")
        self.comboBox_23.setItemText(3, "4")
        self.comboBox_23.setItemText(4, "5")
        self.comboBox_23.setItemText(5, "6")
        self.comboBox_23.setItemText(6, "7")
        self.comboBox_23.setItemText(7, "8")
        self.comboBox_23.setItemText(8, "9")
        self.comboBox_23.setItemText(9, "10")
        self.label_37.setText("天")
        self.label_71.setText("週MACD")
        self.comboBox_26.setItemText(0, ">")
        self.comboBox_26.setItemText(1, ">=")
        self.comboBox_26.setItemText(2, "<")
        self.comboBox_26.setItemText(3, "<=")
        self.comboBox_26.setItemText(4, "<>")
        self.comboBox_26.setItemText(5, "=")
        self.lineEdit_9.setText("0")
        self.label_39.setText(" 連續")
        self.comboBox_27.setItemText(0, "1")
        self.comboBox_27.setItemText(1, "2")
        self.comboBox_27.setItemText(2, "3")
        self.comboBox_27.setItemText(3, "4")
        self.comboBox_27.setItemText(4, "5")
        self.comboBox_27.setItemText(5, "6")
        self.comboBox_27.setItemText(6, "7")
        self.comboBox_27.setItemText(7, "8")
        self.comboBox_27.setItemText(8, "9")
        self.comboBox_27.setItemText(9, "10")
        self.label_40.setText("週")
        self.label_74.setText("月MACD")
        self.comboBox_24.setItemText(0, ">")
        self.comboBox_24.setItemText(1, ">=")
        self.comboBox_24.setItemText(2, "<")
        self.comboBox_24.setItemText(3, "<=")
        self.comboBox_24.setItemText(4, "<>")
        self.comboBox_24.setItemText(5, "=")
        self.lineEdit_8.setText("0")
        self.label_7.setText(" 連續")
        self.comboBox_25.setItemText(0, "1")
        self.comboBox_25.setItemText(1, "2")
        self.comboBox_25.setItemText(2, "3")
        self.comboBox_25.setItemText(3, "4")
        self.comboBox_25.setItemText(4, "5")
        self.comboBox_25.setItemText(5, "6")
        self.comboBox_25.setItemText(6, "7")
        self.comboBox_25.setItemText(7, "8")
        self.comboBox_25.setItemText(8, "9")
        self.comboBox_25.setItemText(9, "10")
        self.label_38.setText("月")
        self.label_77.setText("日DIF")
        self.comboBox_28.setItemText(0, ">")
        self.comboBox_28.setItemText(1, ">=")
        self.comboBox_28.setItemText(2, "<")
        self.comboBox_28.setItemText(3, "<=")
        self.comboBox_28.setItemText(4, "<>")
        self.comboBox_28.setItemText(5, "=")
        self.lineEdit_10.setText("0")
        self.label_41.setText(" 連續")
        self.comboBox_29.setItemText(0, "1")
        self.comboBox_29.setItemText(1, "2")
        self.comboBox_29.setItemText(2, "3")
        self.comboBox_29.setItemText(3, "4")
        self.comboBox_29.setItemText(4, "5")
        self.comboBox_29.setItemText(5, "6")
        self.comboBox_29.setItemText(6, "7")
        self.comboBox_29.setItemText(7, "8")
        self.comboBox_29.setItemText(8, "9")
        self.comboBox_29.setItemText(9, "10")
        self.label_42.setText("天")
        self.label_80.setText("週DIF")
        self.comboBox_32.setItemText(0, ">")
        self.comboBox_32.setItemText(1, ">=")
        self.comboBox_32.setItemText(2, "<")
        self.comboBox_32.setItemText(3, "<=")
        self.comboBox_32.setItemText(4, "<>")
        self.comboBox_32.setItemText(5, "=")
        self.lineEdit_12.setText("0")
        self.label_45.setText(" 連續")
        self.comboBox_33.setItemText(0, "1")
        self.comboBox_33.setItemText(1, "2")
        self.comboBox_33.setItemText(2, "3")
        self.comboBox_33.setItemText(3, "4")
        self.comboBox_33.setItemText(4, "5")
        self.comboBox_33.setItemText(5, "6")
        self.comboBox_33.setItemText(6, "7")
        self.comboBox_33.setItemText(7, "8")
        self.comboBox_33.setItemText(8, "9")
        self.comboBox_33.setItemText(9, "10")
        self.label_46.setText("週")
        self.label_83.setText("月DIF")
        self.comboBox_30.setItemText(0, ">")
        self.comboBox_30.setItemText(1, ">=")
        self.comboBox_30.setItemText(2, "<")
        self.comboBox_30.setItemText(3, "<=")
        self.comboBox_30.setItemText(4, "<>")
        self.comboBox_30.setItemText(5, "=")
        self.lineEdit_11.setText("0")
        self.label_43.setText(" 連續")
        self.comboBox_31.setItemText(0, "1")
        self.comboBox_31.setItemText(1, "2")
        self.comboBox_31.setItemText(2, "3")
        self.comboBox_31.setItemText(3, "4")
        self.comboBox_31.setItemText(4, "5")
        self.comboBox_31.setItemText(5, "6")
        self.comboBox_31.setItemText(6, "7")
        self.comboBox_31.setItemText(7, "8")
        self.comboBox_31.setItemText(8, "9")
        self.comboBox_31.setItemText(9, "10")
        self.label_44.setText("月")
        self.label_122.setText("日RSI(6)")
        self.comboBox_40.setItemText(0, ">")
        self.comboBox_40.setItemText(1, ">=")
        self.comboBox_40.setItemText(2, "<")
        self.comboBox_40.setItemText(3, "<=")
        self.comboBox_40.setItemText(4, "<>")
        self.comboBox_40.setItemText(5, "=")
        self.lineEdit_13.setText("0")
        self.label_60.setText(" 連續")
        self.comboBox_41.setItemText(0, "1")
        self.comboBox_41.setItemText(1, "2")
        self.comboBox_41.setItemText(2, "3")
        self.comboBox_41.setItemText(3, "4")
        self.comboBox_41.setItemText(4, "5")
        self.comboBox_41.setItemText(5, "6")
        self.comboBox_41.setItemText(6, "7")
        self.comboBox_41.setItemText(7, "8")
        self.comboBox_41.setItemText(8, "9")
        self.comboBox_41.setItemText(9, "10")
        self.label_61.setText("日")
        self.label_130.setText("月RSI(6)")
        self.comboBox_42.setItemText(0, ">")
        self.comboBox_42.setItemText(1, ">=")
        self.comboBox_42.setItemText(2, "<")
        self.comboBox_42.setItemText(3, "<=")
        self.comboBox_42.setItemText(4, "<>")
        self.comboBox_42.setItemText(5, "=")
        self.lineEdit_14.setText("0")
        self.label_63.setText(" 連續")
        self.comboBox_43.setItemText(0, "1")
        self.comboBox_43.setItemText(1, "2")
        self.comboBox_43.setItemText(2, "3")
        self.comboBox_43.setItemText(3, "4")
        self.comboBox_43.setItemText(4, "5")
        self.comboBox_43.setItemText(5, "6")
        self.comboBox_43.setItemText(6, "7")
        self.comboBox_43.setItemText(7, "8")
        self.comboBox_43.setItemText(8, "9")
        self.comboBox_43.setItemText(9, "10")
        self.label_64.setText("月")
        self.label_129.setText("週RSI(12)")
        self.comboBox_48.setItemText(0, ">")
        self.comboBox_48.setItemText(1, ">=")
        self.comboBox_48.setItemText(2, "<")
        self.comboBox_48.setItemText(3, "<=")
        self.comboBox_48.setItemText(4, "<>")
        self.comboBox_48.setItemText(5, "=")
        self.lineEdit_17.setText("0")
        self.label_72.setText(" 連續")
        self.comboBox_49.setItemText(0, "1")
        self.comboBox_49.setItemText(1, "2")
        self.comboBox_49.setItemText(2, "3")
        self.comboBox_49.setItemText(3, "4")
        self.comboBox_49.setItemText(4, "5")
        self.comboBox_49.setItemText(5, "6")
        self.comboBox_49.setItemText(6, "7")
        self.comboBox_49.setItemText(7, "8")
        self.comboBox_49.setItemText(8, "9")
        self.comboBox_49.setItemText(9, "10")
        self.label_73.setText("週")
        self.label_212.setText("月成交量")
        self.label_98.setText("連續")
        self.comboBox_75.setItemText(0, "1")
        self.comboBox_75.setItemText(1, "2")
        self.comboBox_75.setItemText(2, "3")
        self.comboBox_75.setItemText(3, "4")
        self.comboBox_75.setItemText(4, "5")
        self.comboBox_75.setItemText(5, "6")
        self.comboBox_75.setItemText(6, "7")
        self.comboBox_75.setItemText(7, "8")
        self.comboBox_75.setItemText(8, "9")
        self.comboBox_75.setItemText(9, "10")
        self.label_99.setText("月")
        self.comboBox_76.setItemText(0, "增加")
        self.comboBox_76.setItemText(1, "減少")
        self.label_210.setText("週成交量")
        self.label_102.setText("連續")
        self.comboBox_77.setItemText(0, "1")
        self.comboBox_77.setItemText(1, "2")
        self.comboBox_77.setItemText(2, "3")
        self.comboBox_77.setItemText(3, "4")
        self.comboBox_77.setItemText(4, "5")
        self.comboBox_77.setItemText(5, "6")
        self.comboBox_77.setItemText(6, "7")
        self.comboBox_77.setItemText(7, "8")
        self.comboBox_77.setItemText(8, "9")
        self.comboBox_77.setItemText(9, "10")
        self.label_101.setText("週")
        self.comboBox_78.setItemText(0, "增加")
        self.comboBox_78.setItemText(1, "減少")
        self.label_208.setText("日成交量")
        self.label_103.setText("連續")
        self.comboBox_74.setItemText(0, "1")
        self.comboBox_74.setItemText(1, "2")
        self.comboBox_74.setItemText(2, "3")
        self.comboBox_74.setItemText(3, "4")
        self.comboBox_74.setItemText(4, "5")
        self.comboBox_74.setItemText(5, "6")
        self.comboBox_74.setItemText(6, "7")
        self.comboBox_74.setItemText(7, "8")
        self.comboBox_74.setItemText(8, "9")
        self.comboBox_74.setItemText(9, "10")
        self.label_97.setText("日")
        self.comboBox_73.setItemText(0, "增加")
        self.comboBox_73.setItemText(1, "減少")
        self.comboBox_91.setItemText(0, "日")
        self.comboBox_91.setItemText(1, "週")
        self.comboBox_91.setItemText(2, "月")
        self.label_82.setText("波動率")
        self.label_115.setText("介於")
        self.lineEdit_24.setText("0")
        self.label_96.setText("%")
        self.label_29.setText(" ~ ")
        self.lineEdit_25.setText("100")
        self.label_95.setText("%")
        self.comboBox_105.setItemText(0, "日")
        self.comboBox_105.setItemText(1, "週")
        self.comboBox_105.setItemText(2, "月")
        self.label_125.setText("MFI(14)")
        self.comboBox_72.setItemText(0, ">")
        self.comboBox_72.setItemText(1, ">=")
        self.comboBox_72.setItemText(2, "<")
        self.comboBox_72.setItemText(3, "<=")
        self.comboBox_72.setItemText(4, "<>")
        self.comboBox_72.setItemText(5, "=")
        self.lineEdit_23.setText("0")
        self.comboBox_92.setItemText(0, "日")
        self.comboBox_92.setItemText(1, "週")
        self.comboBox_92.setItemText(2, "月")
        self.label_81.setText("賣壓比例")
        self.comboBox_71.setItemText(0, ">")
        self.comboBox_71.setItemText(1, ">=")
        self.comboBox_71.setItemText(2, "<")
        self.comboBox_71.setItemText(3, "<=")
        self.comboBox_71.setItemText(4, "<>")
        self.comboBox_71.setItemText(5, "=")
        self.lineEdit_22.setText("0")
        self.label_54.setText("通道開口")
        self.comboBox_70.setItemText(0, "變大")
        self.comboBox_70.setItemText(1, "變小")
        self.label_114.setText("連續")
        self.comboBox_119.setItemText(0, "1")
        self.comboBox_119.setItemText(1, "2")
        self.comboBox_119.setItemText(2, "3")
        self.comboBox_119.setItemText(3, "4")
        self.comboBox_119.setItemText(4, "5")
        self.comboBox_119.setItemText(5, "6")
        self.comboBox_119.setItemText(6, "7")
        self.comboBox_119.setItemText(7, "8")
        self.comboBox_119.setItemText(8, "9")
        self.comboBox_119.setItemText(9, "10")
        self.comboBox_89.setItemText(0, "5 / 20")
        self.comboBox_89.setItemText(1, "5 / 60")
        self.comboBox_89.setItemText(2, "20 / 60")
        self.comboBox_94.setItemText(0, "日")
        self.comboBox_94.setItemText(1, "週")
        self.comboBox_94.setItemText(2, "月")
        self.label_89.setText("均量價死亡交叉")
        self.comboBox_88.setItemText(0, "5 / 20")
        self.comboBox_88.setItemText(1, "5 / 60")
        self.comboBox_88.setItemText(2, "20 / 60")
        self.comboBox_93.setItemText(0, "日")
        self.comboBox_93.setItemText(1, "週")
        self.comboBox_93.setItemText(2, "月")
        self.label_88.setText("均量價黃金交叉")
        self.comboBox_68.setItemText(0, "5 / 20")
        self.comboBox_68.setItemText(1, "5 / 60")
        self.comboBox_68.setItemText(2, "20 / 60")
        self.comboBox_101.setItemText(0, "日")
        self.comboBox_101.setItemText(1, "週")
        self.comboBox_101.setItemText(2, "月")
        self.label_86.setText("均線價黃金交叉")
        self.label_110.setText("月RSI")
        self.comboBox_82.setItemText(0, "黃金交叉")
        self.comboBox_82.setItemText(1, "低於20黃金交叉")
        self.comboBox_82.setItemText(2, "20~50黃金交叉")
        self.comboBox_82.setItemText(3, "50~80黃金交叉")
        self.comboBox_82.setItemText(4, "高於80黃金交叉")
        self.comboBox_82.setItemText(5, "死亡交叉")
        self.comboBox_82.setItemText(6, "低於20死亡交叉")
        self.comboBox_82.setItemText(7, "20~50死亡交叉")
        self.comboBox_82.setItemText(8, "50~80死亡交叉")
        self.comboBox_82.setItemText(9, "高於80死亡交叉")
        self.label_108.setText("週RSI")
        self.comboBox_81.setItemText(0, "黃金交叉")
        self.comboBox_81.setItemText(1, "低於20黃金交叉")
        self.comboBox_81.setItemText(2, "20~50黃金交叉")
        self.comboBox_81.setItemText(3, "50~80黃金交叉")
        self.comboBox_81.setItemText(4, "高於80黃金交叉")
        self.comboBox_81.setItemText(5, "死亡交叉")
        self.comboBox_81.setItemText(6, "低於20死亡交叉")
        self.comboBox_81.setItemText(7, "20~50死亡交叉")
        self.comboBox_81.setItemText(8, "50~80死亡交叉")
        self.comboBox_81.setItemText(9, "高於80死亡交叉")
        self.label_106.setText("日RSI")
        self.comboBox_69.setItemText(0, "黃金交叉")
        self.comboBox_69.setItemText(1, "低於20黃金交叉")
        self.comboBox_69.setItemText(2, "20~50黃金交叉")
        self.comboBox_69.setItemText(3, "50~80黃金交叉")
        self.comboBox_69.setItemText(4, "高於80黃金交叉")
        self.comboBox_69.setItemText(5, "死亡交叉")
        self.comboBox_69.setItemText(6, "低於20死亡交叉")
        self.comboBox_69.setItemText(7, "20~50死亡交叉")
        self.comboBox_69.setItemText(8, "50~80死亡交叉")
        self.comboBox_69.setItemText(9, "高於80死亡交叉")
        self.label_136.setText("外資")
        self.label_112.setText("連續")
        self.comboBox_97.setItemText(0, "買超")
        self.comboBox_97.setItemText(1, "賣超")
        self.comboBox_98.setItemText(0, "1")
        self.comboBox_98.setItemText(1, "2")
        self.comboBox_98.setItemText(2, "3")
        self.comboBox_98.setItemText(3, "4")
        self.comboBox_98.setItemText(4, "5")
        self.comboBox_98.setItemText(5, "6")
        self.comboBox_98.setItemText(6, "7")
        self.comboBox_98.setItemText(7, "8")
        self.comboBox_98.setItemText(8, "9")
        self.comboBox_98.setItemText(9, "10")
        self.label_70.setText("日")
        self.label_100.setText("自營商")
        self.label_111.setText("連續")
        self.comboBox_95.setItemText(0, "買超")
        self.comboBox_95.setItemText(1, "賣超")
        self.comboBox_96.setItemText(0, "1")
        self.comboBox_96.setItemText(1, "2")
        self.comboBox_96.setItemText(2, "3")
        self.comboBox_96.setItemText(3, "4")
        self.comboBox_96.setItemText(4, "5")
        self.comboBox_96.setItemText(5, "6")
        self.comboBox_96.setItemText(6, "7")
        self.comboBox_96.setItemText(7, "8")
        self.comboBox_96.setItemText(8, "9")
        self.comboBox_96.setItemText(9, "10")
        self.label_69.setText("日")
        self.label_118.setText("投信")
        self.label_113.setText("連續")
        self.comboBox_85.setItemText(0, "買超")
        self.comboBox_85.setItemText(1, "賣超")
        self.comboBox_86.setItemText(0, "1")
        self.comboBox_86.setItemText(1, "2")
        self.comboBox_86.setItemText(2, "3")
        self.comboBox_86.setItemText(3, "4")
        self.comboBox_86.setItemText(4, "5")
        self.comboBox_86.setItemText(5, "6")
        self.comboBox_86.setItemText(6, "7")
        self.comboBox_86.setItemText(7, "8")
        self.comboBox_86.setItemText(8, "9")
        self.comboBox_86.setItemText(9, "10")
        self.label_75.setText("日")
        self.label_124.setText("三大法人")
        self.label_109.setText("連續")
        self.comboBox_79.setItemText(0, "買超")
        self.comboBox_79.setItemText(1, "賣超")
        self.comboBox_80.setItemText(0, "1")
        self.comboBox_80.setItemText(1, "2")
        self.comboBox_80.setItemText(2, "3")
        self.comboBox_80.setItemText(3, "4")
        self.comboBox_80.setItemText(4, "5")
        self.comboBox_80.setItemText(5, "6")
        self.comboBox_80.setItemText(6, "7")
        self.comboBox_80.setItemText(7, "8")
        self.comboBox_80.setItemText(8, "9")
        self.comboBox_80.setItemText(9, "10")
        self.label_67.setText("日")
        self.label_209.setText("融券")
        self.label_105.setText("連續")
        self.comboBox_117.setItemText(0, "增加")
        self.comboBox_117.setItemText(1, "減少")
        self.comboBox_118.setItemText(0, "1")
        self.comboBox_118.setItemText(1, "2")
        self.comboBox_118.setItemText(2, "3")
        self.comboBox_118.setItemText(3, "4")
        self.comboBox_118.setItemText(4, "5")
        self.comboBox_118.setItemText(5, "6")
        self.comboBox_118.setItemText(6, "7")
        self.comboBox_118.setItemText(7, "8")
        self.comboBox_118.setItemText(8, "9")
        self.comboBox_118.setItemText(9, "10")
        self.label_79.setText("日")
        self.label_168.setText("融資")
        self.label_104.setText("連續")
        self.comboBox_113.setItemText(0, "增加")
        self.comboBox_113.setItemText(1, "減少")
        self.comboBox_114.setItemText(0, "1")
        self.comboBox_114.setItemText(1, "2")
        self.comboBox_114.setItemText(2, "3")
        self.comboBox_114.setItemText(3, "4")
        self.comboBox_114.setItemText(4, "5")
        self.comboBox_114.setItemText(5, "6")
        self.comboBox_114.setItemText(6, "7")
        self.comboBox_114.setItemText(7, "8")
        self.comboBox_114.setItemText(8, "9")
        self.comboBox_114.setItemText(9, "10")
        self.label_78.setText("日")
        self.label_140.setText("券資比")
        self.label_107.setText("連續")
        self.comboBox_103.setItemText(0, "增加")
        self.comboBox_103.setItemText(1, "減少")
        self.comboBox_104.setItemText(0, "1")
        self.comboBox_104.setItemText(1, "2")
        self.comboBox_104.setItemText(2, "3")
        self.comboBox_104.setItemText(3, "4")
        self.comboBox_104.setItemText(4, "5")
        self.comboBox_104.setItemText(5, "6")
        self.comboBox_104.setItemText(6, "7")
        self.comboBox_104.setItemText(7, "8")
        self.comboBox_104.setItemText(8, "9")
        self.comboBox_104.setItemText(9, "10")
        self.label_76.setText("日")
        self.label_47.setText("週K")
        self.comboBox_10.setItemText(0, ">")
        self.comboBox_10.setItemText(1, ">=")
        self.comboBox_10.setItemText(2, "<")
        self.comboBox_10.setItemText(3, "<=")
        self.comboBox_10.setItemText(4, "<>")
        self.comboBox_10.setItemText(5, "=")
        self.lineEdit_4.setText("0")
        self.label_32.setText(" 連續")
        self.comboBox_12.setItemText(0, "1")
        self.comboBox_12.setItemText(1, "2")
        self.comboBox_12.setItemText(2, "3")
        self.comboBox_12.setItemText(3, "4")
        self.comboBox_12.setItemText(4, "5")
        self.comboBox_12.setItemText(5, "6")
        self.comboBox_12.setItemText(6, "7")
        self.comboBox_12.setItemText(7, "8")
        self.comboBox_12.setItemText(8, "9")
        self.comboBox_12.setItemText(9, "10")
        self.label_33.setText("週")
        self.label_49.setText("日K")
        self.comboBox_7.setItemText(0, ">")
        self.comboBox_7.setItemText(1, ">=")
        self.comboBox_7.setItemText(2, "<")
        self.comboBox_7.setItemText(3, "<=")
        self.comboBox_7.setItemText(4, "<>")
        self.comboBox_7.setItemText(5, "=")
        self.lineEdit_2.setText("0")
        self.label_27.setText(" 連續")
        self.comboBox_9.setItemText(0, "1")
        self.comboBox_9.setItemText(1, "2")
        self.comboBox_9.setItemText(2, "3")
        self.comboBox_9.setItemText(3, "4")
        self.comboBox_9.setItemText(4, "5")
        self.comboBox_9.setItemText(5, "6")
        self.comboBox_9.setItemText(6, "7")
        self.comboBox_9.setItemText(7, "8")
        self.comboBox_9.setItemText(8, "9")
        self.comboBox_9.setItemText(9, "10")
        self.label_28.setText("天")
        self.comboBox_65.setItemText(0, "5 / 20")
        self.comboBox_65.setItemText(1, "5 / 60")
        self.comboBox_65.setItemText(2, "20 / 60")
        self.comboBox_102.setItemText(0, "日")
        self.comboBox_102.setItemText(1, "週")
        self.comboBox_102.setItemText(2, "月")
        self.label_87.setText("均線價死亡交叉")
        self.label_137.setText("通道股價")
        self.comboBox_99.setItemText(0, "突破")
        self.comboBox_99.setItemText(1, "跌破")
        self.comboBox_100.setItemText(0, "1")
        self.comboBox_100.setItemText(1, "2")
        self.comboBox_100.setItemText(2, "3")
        self.comboBox_100.setItemText(3, "4")
        self.comboBox_100.setItemText(4, "5")
        self.label_34.setText("個標準差")
        self.label_126.setText("日RSI(12)")
        self.comboBox_46.setItemText(0, ">")
        self.comboBox_46.setItemText(1, ">=")
        self.comboBox_46.setItemText(2, "<")
        self.comboBox_46.setItemText(3, "<=")
        self.comboBox_46.setItemText(4, "<>")
        self.comboBox_46.setItemText(5, "=")
        self.lineEdit_15.setText("0")
        self.label_84.setText(" 連續")
        self.comboBox_47.setItemText(0, "1")
        self.comboBox_47.setItemText(1, "2")
        self.comboBox_47.setItemText(2, "3")
        self.comboBox_47.setItemText(3, "4")
        self.comboBox_47.setItemText(4, "5")
        self.comboBox_47.setItemText(5, "6")
        self.comboBox_47.setItemText(6, "7")
        self.comboBox_47.setItemText(7, "8")
        self.comboBox_47.setItemText(8, "9")
        self.comboBox_47.setItemText(9, "10")
        self.label_85.setText("日")
        self.label_123.setText("日RSI(9)")
        self.comboBox_50.setItemText(0, ">")
        self.comboBox_50.setItemText(1, ">=")
        self.comboBox_50.setItemText(2, "<")
        self.comboBox_50.setItemText(3, "<=")
        self.comboBox_50.setItemText(4, "<>")
        self.comboBox_50.setItemText(5, "=")
        self.lineEdit_16.setText("0")
        self.label_90.setText(" 連續")
        self.comboBox_51.setItemText(0, "1")
        self.comboBox_51.setItemText(1, "2")
        self.comboBox_51.setItemText(2, "3")
        self.comboBox_51.setItemText(3, "4")
        self.comboBox_51.setItemText(4, "5")
        self.comboBox_51.setItemText(5, "6")
        self.comboBox_51.setItemText(6, "7")
        self.comboBox_51.setItemText(7, "8")
        self.comboBox_51.setItemText(8, "9")
        self.comboBox_51.setItemText(9, "10")
        self.label_91.setText("日")
        self.label_127.setText("週RSI(6)")
        self.comboBox_52.setItemText(0, ">")
        self.comboBox_52.setItemText(1, ">=")
        self.comboBox_52.setItemText(2, "<")
        self.comboBox_52.setItemText(3, "<=")
        self.comboBox_52.setItemText(4, "<>")
        self.comboBox_52.setItemText(5, "=")
        self.lineEdit_18.setText("0")
        self.label_92.setText(" 連續")
        self.comboBox_53.setItemText(0, "1")
        self.comboBox_53.setItemText(1, "2")
        self.comboBox_53.setItemText(2, "3")
        self.comboBox_53.setItemText(3, "4")
        self.comboBox_53.setItemText(4, "5")
        self.comboBox_53.setItemText(5, "6")
        self.comboBox_53.setItemText(6, "7")
        self.comboBox_53.setItemText(7, "8")
        self.comboBox_53.setItemText(8, "9")
        self.comboBox_53.setItemText(9, "10")
        self.label_93.setText("週")
        self.label_128.setText("週RSI(9)")
        self.comboBox_54.setItemText(0, ">")
        self.comboBox_54.setItemText(1, ">=")
        self.comboBox_54.setItemText(2, "<")
        self.comboBox_54.setItemText(3, "<=")
        self.comboBox_54.setItemText(4, "<>")
        self.comboBox_54.setItemText(5, "=")
        self.lineEdit_19.setText("0")
        self.label_94.setText(" 連續")
        self.comboBox_55.setItemText(0, "1")
        self.comboBox_55.setItemText(1, "2")
        self.comboBox_55.setItemText(2, "3")
        self.comboBox_55.setItemText(3, "4")
        self.comboBox_55.setItemText(4, "5")
        self.comboBox_55.setItemText(5, "6")
        self.comboBox_55.setItemText(6, "7")
        self.comboBox_55.setItemText(7, "8")
        self.comboBox_55.setItemText(8, "9")
        self.comboBox_55.setItemText(9, "10")
        self.label_116.setText("週")
        self.label_131.setText("月RSI(9)")
        self.comboBox_56.setItemText(0, ">")
        self.comboBox_56.setItemText(1, ">=")
        self.comboBox_56.setItemText(2, "<")
        self.comboBox_56.setItemText(3, "<=")
        self.comboBox_56.setItemText(4, "<>")
        self.comboBox_56.setItemText(5, "=")
        self.lineEdit_20.setText("0")
        self.label_117.setText(" 連續")
        self.comboBox_57.setItemText(0, "1")
        self.comboBox_57.setItemText(1, "2")
        self.comboBox_57.setItemText(2, "3")
        self.comboBox_57.setItemText(3, "4")
        self.comboBox_57.setItemText(4, "5")
        self.comboBox_57.setItemText(5, "6")
        self.comboBox_57.setItemText(6, "7")
        self.comboBox_57.setItemText(7, "8")
        self.comboBox_57.setItemText(8, "9")
        self.comboBox_57.setItemText(9, "10")
        self.label_119.setText("月")
        self.label_132.setText("月RSI(12)")
        self.comboBox_58.setItemText(0, ">")
        self.comboBox_58.setItemText(1, ">=")
        self.comboBox_58.setItemText(2, "<")
        self.comboBox_58.setItemText(3, "<=")
        self.comboBox_58.setItemText(4, "<>")
        self.comboBox_58.setItemText(5, "=")
        self.lineEdit_21.setText("0")
        self.label_120.setText(" 連續")
        self.comboBox_59.setItemText(0, "1")
        self.comboBox_59.setItemText(1, "2")
        self.comboBox_59.setItemText(2, "3")
        self.comboBox_59.setItemText(3, "4")
        self.comboBox_59.setItemText(4, "5")
        self.comboBox_59.setItemText(5, "6")
        self.comboBox_59.setItemText(6, "7")
        self.comboBox_59.setItemText(7, "8")
        self.comboBox_59.setItemText(8, "9")
        self.comboBox_59.setItemText(9, "10")
        self.label_121.setText("月")