# Generated by Django 3.0.1 on 2019-12-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_poem'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
