# Generated by Django 3.0.1 on 2020-09-27 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20200912_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poem',
            old_name='author',
            new_name='authorname',
        ),
    ]
