# Generated by Django 3.0.1 on 2020-09-27 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20200927_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.Author'),
            preserve_default=False,
        ),
    ]
