# Generated by Django 3.0.1 on 2020-10-20 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album2Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Album')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Poem')),
            ],
        ),
    ]
