# Generated by Django 2.2.5 on 2020-10-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='anthology',
            field=models.TextField(default=0),
        ),
    ]
