# Generated by Django 2.2.3 on 2020-11-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_album_anthology'),
        ('mysite', '0011_book_poemeng'),
    ]

    operations = [
    ]
