# Generated by Django 3.1.3 on 2020-11-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_album_anthology'),
        ('mysite', '0011_book_poemeng'),
    ]

    operations = [
    ]
