# Generated by Django 2.2.3 on 2020-11-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_merge_20201106_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='poemeng',
            name='fcontent',
            field=models.TextField(null=True),
        ),
    ]
