# Generated by Django 2.2.3 on 2020-11-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_poemeng_fcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='poemeng',
            name='memo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
