# Generated by Django 2.2.3 on 2020-11-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_poemeng_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poemeng',
            name='memo',
        ),
    ]
