# Generated by Django 3.0.1 on 2020-12-23 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_remove_poemeng_memo'),
        ('mysite', '0012_merge_20201121_1614'),
    ]

    operations = [
    ]
