# Generated by Django 3.0.1 on 2020-12-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_merge_20201224_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poemeng',
            name='fcontent',
        ),
        migrations.AddField(
            model_name='book',
            name='pub_year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
