# Generated by Django 3.0.1 on 2020-12-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_poem_cutted'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
