# Generated by Django 3.0.1 on 2020-12-27 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_author_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookJpn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('pub_year', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PoemJpn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.BookJpn')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Poem')),
            ],
        ),
    ]
