# Generated by Django 3.0.1 on 2021-02-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_bookjpn_poemjpn'),
    ]

    operations = [
        migrations.AddField(
            model_name='poemjpn',
            name='feature',
            field=models.CharField(default='000000', max_length=255),
        ),
        migrations.AddField(
            model_name='poemjpn',
            name='page',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poemjpn',
            name='translator',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='poemjpn',
            name='title',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
