# Generated by Django 3.0.1 on 2021-02-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_auto_20210204_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='poemjpn',
            name='formatted_content',
            field=models.TextField(default='null'),
        ),
    ]
