# Generated by Django 3.0.1 on 2021-02-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_poemjpn_formatted_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='style',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
