# Generated by Django 3.0.1 on 2021-02-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_poem_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='poemeng',
            name='feature',
            field=models.CharField(default='000000', max_length=255),
        ),
        migrations.AddField(
            model_name='poemeng',
            name='formatted_content',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='poemeng',
            name='page',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poemeng',
            name='translator',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
