# Generated by Django 3.0.1 on 2021-02-06 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_auto_20210205_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poem',
            name='created_by',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='poemeng',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poemeng',
            name='created_by',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='poemjpn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poemjpn',
            name='created_by',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
