# Generated by Django 3.0.1 on 2021-03-09 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_auto_20210206_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynasty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_dynasty', models.CharField(default='abc', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='dynasty',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='mysite.Dynasty'),
        ),
    ]
