# Generated by Django 3.0.1 on 2021-03-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_auto_20210309_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='captured',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='poemjpn',
            name='style',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='poem',
            name='style',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
