# Generated by Django 2.2.7 on 2020-03-29 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_language', models.CharField(max_length=10)),
                ('tag_level', models.CharField(max_length=10)),
                ('tag_is_chinese', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Video_Tube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now_add=True)),
                ('watch_number', models.IntegerField(default=0)),
                ('video_id', models.CharField(max_length=50, null=True)),
                ('video_url', models.CharField(max_length=200, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='videos.Video_Tag')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Video_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WatchNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_number', models.IntegerField(default=0)),
                ('video', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='videos.Video_Tube')),
            ],
        ),
        migrations.AddField(
            model_name='video_tube',
            name='video_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='videos.Video_Type'),
        ),
    ]
