# Generated by Django 2.2.7 on 2020-03-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_tube',
            name='watch_number',
        ),
    ]
