# Generated by Django 2.1.7 on 2019-07-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boss',
            old_name='pub_date',
            new_name='pub_date3',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='pub_date',
            new_name='pub_date1',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='pub_date',
            new_name='pub_date2',
        ),
    ]
