# Generated by Django 2.1.7 on 2019-07-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0002_auto_20190715_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basicinformation', models.CharField(max_length=10)),
                ('schoolinformation', models.CharField(max_length=10)),
                ('workinformation', models.CharField(max_length=10)),
                ('sandybossinformation', models.CharField(max_length=10)),
            ],
        ),
    ]
