# Generated by Django 2.1.7 on 2019-07-17 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0003_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
