# Generated by Django 2.2.3 on 2019-09-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0007_auto_20190725_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='email',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
