# Generated by Django 2.2.3 on 2019-09-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0008_home_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='abc',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
