# Generated by Django 2.2.5 on 2019-09-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0009_home_abc'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='dick',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
