# Generated by Django 2.2.5 on 2019-09-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0010_home_dick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='basicinformation',
        ),
    ]
