# Generated by Django 2.2.5 on 2019-09-17 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0010_remove_home_abc'),
        ('firstblog', '0011_remove_home_basicinformation'),
    ]

    operations = [
    ]
