# Generated by Django 2.2.5 on 2019-09-17 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0012_merge_20190917_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='dick',
            new_name='basicinformation',
        ),
    ]
