# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stock_class.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QHeaderView
import pymysql.cursors
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *

class myLabel(QLabel):
    clicked = pyqtSignal()
    def mouseReleaseEvent(self, QMouseEvent):
        if QMouseEvent.button() == Qt.LeftButton:
            self.clicked.emit()

class Ui_Stock_Class(object):
	def setupUi(self, MainWindow):
		db = pymysql.connect(
			host='127.0.0.1',
			user='root',
			password='',
			database="stock",
			port=3306
		)
		cursor = db.cursor()
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(1600, 900)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.verticalLayout = QtWidgets.QVBoxLayout()
		self.verticalLayout.setObjectName("verticalLayout")
		self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")

		self.label = QtWidgets.QLabel(self.centralwidget)
		self.label.setObjectName("label")
		self.horizontalLayout_3.addWidget(self.label)
		self.comboBox = QtWidgets.QComboBox(self.centralwidget)
		self.comboBox.setMinimumSize(QtCore.QSize(150, 20))
		self.comboBox.setMaximumSize(QtCore.QSize(150, 20))
		self.comboBox.setObjectName("comboBox")
		self.class_stock = '''SELECT * FROM classification'''
		cursor.execute(self.class_stock)
		stock_list = cursor.fetchall()
		for stock_1,stock_2 in stock_list:
			self.comboBox.addItem(stock_2)
		self.horizontalLayout_3.addWidget(self.comboBox)
		spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_3.addItem(spacerItem1)
		self.verticalLayout.addLayout(self.horizontalLayout_3)
		self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
		self.lineEdit.setObjectName("lineEdit")
		self.lineEdit.setMinimumSize(QtCore.QSize(100, 20))
		self.lineEdit.setMaximumSize(QtCore.QSize(100, 20))
		self.label_2 = myLabel(self.centralwidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
		self.label_2.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.label_2.setFont(font)
		self.label_2.setAlignment(QtCore.Qt.AlignCenter)
		self.label_2.setObjectName("label_2")
		self.label_3 = QtWidgets.QLabel(self.centralwidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
		self.label_3.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setPointSize(15)
		self.label_3.setFont(font)
		self.label_3.setObjectName("label_3")
		self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
		self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
		self.tableWidget.setAlternatingRowColors(False)
		self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
		self.tableWidget.setShowGrid(True)
		self.tableWidget.setWordWrap(True)
		self.tableWidget.setCornerButtonEnabled(True)
		self.tableWidget.setRowCount(30)
		self.tableWidget.setColumnCount(10)
		self.tableWidget.setObjectName("tableWidget")
		self.tableWidget.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setVerticalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setVerticalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		font = QtGui.QFont()
		font.setPointSize(15)
		item.setFont(font)
		self.tableWidget.setItem(0, 0, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		font = QtGui.QFont()
		font.setPointSize(15)
		item.setFont(font)
		self.tableWidget.setItem(0, 1, item)
		item = QtWidgets.QTableWidgetItem()
		item.setTextAlignment(QtCore.Qt.AlignCenter)
		font = QtGui.QFont()
		font.setPointSize(15)
		item.setFont(font)
		self.tableWidget.setItem(0, 2, item)
		self.tableWidget.horizontalHeader().setVisible(True)
		self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
		self.tableWidget.horizontalHeader().setDefaultSectionSize(110)
		self.tableWidget.horizontalHeader().setHighlightSections(True)
		self.tableWidget.horizontalHeader().setMinimumSectionSize(25)
		self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
		self.tableWidget.horizontalHeader().setStretchLastSection(False)
		self.tableWidget.verticalHeader().setVisible(False)
		self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
		self.tableWidget.verticalHeader().setDefaultSectionSize(30)
		self.tableWidget.verticalHeader().setHighlightSections(False)
		self.tableWidget.verticalHeader().setMinimumSectionSize(10)
		self.tableWidget.verticalHeader().setSortIndicatorShown(False)
		self.tableWidget.verticalHeader().setStretchLastSection(False)
		self.verticalLayout.addWidget(self.tableWidget)
		self.horizontalLayout.addLayout(self.verticalLayout)
		MainWindow.setCentralWidget(self.centralwidget)
		self.toolBar = QtWidgets.QToolBar(MainWindow)
		self.toolBar.setObjectName("toolBar")
		MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
		self.actionhome = QtWidgets.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/icon/house.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionhome.setIcon(icon)
		self.actionhome.setObjectName("actionhome")
		self.actionback = QtWidgets.QAction(MainWindow)
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap(":/icon/iconfinder_restart-1_18208.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionback.setIcon(icon1)
		self.actionback.setObjectName("actionback")
		self.actionnext = QtWidgets.QAction(MainWindow)
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap(":/icon/iconfinder_restart-1_18209.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionnext.setIcon(icon2)
		self.actionnext.setObjectName("actionnext")
		self.actionenter = QtWidgets.QAction(MainWindow)
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap(":/icon/enter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionenter.setIcon(icon3)
		self.actionenter.setObjectName("actionenter")
		self.toolBar.addAction(self.actionhome)
		self.toolBar.addSeparator()
		self.toolBar.addAction(self.actionback)
		self.toolBar.addAction(self.actionnext)
		self.toolBar.addSeparator()
		self.toolBar.addWidget(self.label_2)
		self.toolBar.addWidget(self.label_3)
		self.toolBar.addWidget(self.lineEdit)
		self.toolBar.addAction(self.actionenter)
		
		for i in range(0,10):
			total = ['股票代碼','日期','成交股數','成交金額','開盤價','最高價','最低價','收盤價','漲跌價差','成交筆數']
			newItem = QTableWidgetItem(total[i])
			font = QFont()
			font.setPointSize(20)
			self.tableWidget.setHorizontalHeaderItem(i,newItem)
			stylesheet = "::section{Background-color:rgb(148, 148, 255)}"
			self.tableWidget.horizontalHeader().setStyleSheet(stylesheet)
			self.tableWidget.horizontalHeader().setFont(font)
		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
		self.label.setText(_translate("MainWindow", "類別："))
		self.label_2.setText(_translate("MainWindow", "加 權 指 數：16000"))
		self.label_3.setText(_translate("MainWindow", "代碼："))
		self.tableWidget.setSortingEnabled(False)
		__sortingEnabled = self.tableWidget.isSortingEnabled()
		self.tableWidget.setSortingEnabled(False)
		self.tableWidget.setSortingEnabled(__sortingEnabled)
		self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
		self.actionhome.setText(_translate("MainWindow", "home"))
		self.actionback.setText(_translate("MainWindow", "back"))
		self.actionnext.setText(_translate("MainWindow", "next"))
		self.actionenter.setText(_translate("MainWindow", "enter"))
from ui_folder import icons
